import { useMemo } from 'react';
import type {
  NoteViewEditorLayout,
  NoteViewEditorData,
  NoteViewEditorHandlers,
  NoteViewEditorAreaProps,
} from './NoteViewEditorArea';

export type UseNoteViewEditorAreaPropsInput = NoteViewEditorLayout & NoteViewEditorData & NoteViewEditorHandlers;

export function useNoteViewEditorAreaProps(input: UseNoteViewEditorAreaPropsInput): NoteViewEditorAreaProps {
  const {
    hideEditorArea,
    isMobile,
    isCompactChrome,
    isFocusPresetActive,
    isTrash,
    showRightPanel,
    viewMode,
    showAppearance,
    isDragOver,
    headerTagsExpanded,
    docCopied,
    dark,
    c,
    activeNote,
    activeNoteId,
    notes,
    folders,
    titleDraft,
    activeNoteKind,
    noteTags,
    syncError,
    isSyncing,
    savedAt,
    viewModes,
    noteAreaProperty,
    noteLinkedProjectTitle,
    noteLinkedProjectId,
    noteLearningPathLabel,
    noteContextReviewEntry,
    noteConnectionCount,
    noteCosmosTier,
    activeTag,
    searchQuery,
    searchScope,
    searchMatchIdx,
    editorSearchQuery,
    blockColors,
    wikiTargets,
    appSettings,
    knowledgeTimeline,
    activeFocusPreset,
    titleInputRef,
    titleComposingRef,
    blockEditorRef,
    editorScrollRef,
    virtualScrollApiRef,
    searchInputRef,
    importInputRef,
    setMobileShowEditor,
    setActiveNoteId,
    handleExitFocusPreset,
    handleTitleChange,
    handleTitleCompositionEnd,
    noteUpdate,
    retrySync,
    setViewMode,
    openEditEventDialog,
    openMilestoneDialog,
    handleToggleAreaNote,
    toggleStar,
    duplicateNote,
    setShowRightPanel,
    handleCopyDocument,
    exportNote,
    restoreNote,
    moveNoteToTrash,
    setActiveFolderId,
    setSearchQuery,
    setActiveTag,
    setHeaderTagsExpanded,
    openContextPanel,
    setRightPanel,
    handlePromoteNoteKind,
    handleLearnLinking,
    handleHudReviewWeakAreas,
    handleOpenDiscover,
    handleOpenTimeline,
    createNote,
    setSearchScope,
    setSearchMatchIdx,
    insertEmptyImageBlockAtCursor,
    setShowAppearance,
    updateSetting,
    setIsDragOver,
    insertImageAtCursor,
    handleEditorDrop,
    handleReadingModeClick,
    handleActiveBodyChange,
    navigateToWiki,
  } = input;

  return useMemo(() => ({
    layout: {
      hideEditorArea,
      isMobile,
      isCompactChrome,
      isFocusPresetActive,
      isTrash,
      showRightPanel,
      viewMode,
      showAppearance,
      isDragOver,
      headerTagsExpanded,
      docCopied,
      dark,
    },
    data: {
      c,
      activeNote,
      activeNoteId,
      notes,
      folders,
      titleDraft,
      activeNoteKind,
      noteTags,
      syncError,
      isSyncing,
      savedAt,
      viewModes,
      noteAreaProperty,
      noteLinkedProjectTitle,
      noteLinkedProjectId,
      noteLearningPathLabel,
      noteContextReviewEntry,
      noteConnectionCount,
      noteCosmosTier,
      activeTag,
      searchQuery,
      searchScope,
      searchMatchIdx,
      editorSearchQuery,
      blockColors,
      wikiTargets,
      appSettings,
      knowledgeTimeline,
      activeFocusPreset,
    },
    handlers: {
      titleInputRef,
      titleComposingRef,
      blockEditorRef,
      editorScrollRef,
      virtualScrollApiRef,
      searchInputRef,
      importInputRef,
      setMobileShowEditor,
      setActiveNoteId,
      handleExitFocusPreset,
      handleTitleChange,
      handleTitleCompositionEnd,
      noteUpdate,
      retrySync,
      setViewMode,
      openEditEventDialog,
      openMilestoneDialog,
      handleToggleAreaNote,
      toggleStar,
      duplicateNote,
      setShowRightPanel,
      handleCopyDocument,
      exportNote,
      restoreNote,
      moveNoteToTrash,
      setActiveFolderId,
      setSearchQuery,
      setActiveTag,
      setHeaderTagsExpanded,
      openContextPanel,
      setRightPanel,
      handlePromoteNoteKind,
      handleLearnLinking,
      handleHudReviewWeakAreas,
      handleOpenDiscover,
      handleOpenTimeline,
      createNote,
      setSearchScope,
      setSearchMatchIdx,
      insertEmptyImageBlockAtCursor,
      setShowAppearance,
      updateSetting,
      setIsDragOver,
      insertImageAtCursor,
      handleEditorDrop,
      handleReadingModeClick,
      handleActiveBodyChange,
      navigateToWiki,
    },
  }), [
    hideEditorArea, isMobile, isCompactChrome, isFocusPresetActive, isTrash, showRightPanel,
    viewMode, showAppearance, isDragOver, headerTagsExpanded, docCopied, dark, c, activeNote,
    activeNoteId, notes, folders, titleDraft, activeNoteKind, noteTags, syncError, isSyncing,
    savedAt, viewModes, noteAreaProperty, noteLinkedProjectTitle, noteLinkedProjectId,
    noteLearningPathLabel, noteContextReviewEntry, noteConnectionCount, noteCosmosTier, activeTag,
    searchQuery, searchScope, searchMatchIdx, editorSearchQuery, blockColors, wikiTargets,
    appSettings, knowledgeTimeline, activeFocusPreset, titleInputRef, titleComposingRef,
    blockEditorRef, editorScrollRef, virtualScrollApiRef, searchInputRef, importInputRef,
    setMobileShowEditor, setActiveNoteId, handleExitFocusPreset, handleTitleChange,
    handleTitleCompositionEnd, noteUpdate, retrySync, setViewMode, openEditEventDialog,
    openMilestoneDialog, handleToggleAreaNote, toggleStar, duplicateNote, setShowRightPanel,
    handleCopyDocument, exportNote, restoreNote, moveNoteToTrash, setActiveFolderId, setSearchQuery,
    setActiveTag, setHeaderTagsExpanded, openContextPanel, setRightPanel, handlePromoteNoteKind,
    handleLearnLinking, handleHudReviewWeakAreas, handleOpenDiscover, handleOpenTimeline, createNote,
    setSearchScope, setSearchMatchIdx, insertEmptyImageBlockAtCursor, setShowAppearance, updateSetting,
    setIsDragOver, insertImageAtCursor, handleEditorDrop, handleReadingModeClick, handleActiveBodyChange,
    navigateToWiki,
  ]);
}
