import {
  useNoteCrudActions,
  useNoteImportExportActions,
  useNoteTraceActions,
  useNoteKeyboardActions,
  type UseNoteViewActionsParams,
} from './actions';

export type { UseNoteViewActionsParams } from './actions';

export function useNoteViewActions(params: UseNoteViewActionsParams) {
  const crud = useNoteCrudActions(params);
  const importExport = useNoteImportExportActions(params);
  const trace = useNoteTraceActions(params, crud.openCreatedNote);
  const keyboard = useNoteKeyboardActions(params, crud.createNote, crud.duplicateNote);

  return {
    noteUpdate: crud.noteUpdate,
    createNote: crud.createNote,
    duplicateNote: crud.duplicateNote,
    createFolder: crud.createFolder,
    deleteFolder: crud.deleteFolder,
    exportNote: importExport.exportNote,
    exportAllNotes: importExport.exportAllNotes,
    exportVaultBackup: importExport.exportVaultBackup,
    openTraceDay: trace.openTraceDay,
    openTraceRange: trace.openTraceRange,
    openTraceArea: trace.openTraceArea,
    openTraceDiscovery: trace.openTraceDiscovery,
    closeTraceLens: trace.closeTraceLens,
    openCreateEventDialog: trace.openCreateEventDialog,
    openEditEventDialog: trace.openEditEventDialog,
    openMilestoneDialog: trace.openMilestoneDialog,
    handleEventDialogSave: trace.handleEventDialogSave,
    handleRemoveEventStatus: trace.handleRemoveEventStatus,
    handleMilestoneDialogSave: trace.handleMilestoneDialogSave,
    handleRemoveMilestone: trace.handleRemoveMilestone,
    createQuickCapture: crud.createQuickCapture,
    createTask: crud.createTask,
    createJournal: crud.createJournal,
    handleCreateReadingNote: crud.handleCreateReadingNote,
    handleCreateStudyNote: crud.handleCreateStudyNote,
    handleCreateProject: crud.handleCreateProject,
    handleSubmitCreateProject: crud.handleSubmitCreateProject,
    handleCreateProjectMilestone: crud.handleCreateProjectMilestone,
    handleSubmitCreateMilestone: crud.handleSubmitCreateMilestone,
    handleOpenStudyCollection: trace.handleOpenStudyCollection,
    handleOpenResearchCollection: trace.handleOpenResearchCollection,
    handleActivateSubjectWorkspace: trace.handleActivateSubjectWorkspace,
    handleWorkspaceSearchNote: trace.handleWorkspaceSearchNote,
    handleWorkspaceSearchFolder: trace.handleWorkspaceSearchFolder,
    handleWorkspaceSearchTag: trace.handleWorkspaceSearchTag,
    handleWorkspaceSearchCollection: trace.handleWorkspaceSearchCollection,
    handleWorkspaceSearchLearningPath: trace.handleWorkspaceSearchLearningPath,
    handleOpenProjectNotes: trace.handleOpenProjectNotes,
    handleNavigateToProjectEditor: trace.handleNavigateToProjectEditor,
    handleEditProject: trace.handleEditProject,
    handleUpdateProjectDescription: crud.handleUpdateProjectDescription,
    handleUpdateProjectStatus: crud.handleUpdateProjectStatus,
    handleUpdateMilestoneStatus: crud.handleUpdateMilestoneStatus,
    handleUpdateMilestoneTargetDate: crud.handleUpdateMilestoneTargetDate,
    handleCreateLearningPathStepNote: crud.handleCreateLearningPathStepNote,
    handleUpdateNoteProperties: crud.handleUpdateNoteProperties,
    handleActivateDashboardWithTraceClear: trace.handleActivateDashboardWithTraceClear,
    handleCopyDocument: importExport.handleCopyDocument,
    handleTitleChange: crud.handleTitleChange,
    handleTitleCompositionEnd: crud.handleTitleCompositionEnd,
    handleActiveBodyChange: crud.handleActiveBodyChange,
    handlePromoteNoteKind: crud.handlePromoteNoteKind,
    handleLinkReadingSource: crud.handleLinkReadingSource,
    handleUnlinkReadingSource: crud.handleUnlinkReadingSource,
    handleExpandGraphNode: crud.handleExpandGraphNode,
    handleCollapseGraphNode: crud.handleCollapseGraphNode,
    addFolder: crud.addFolder,
    insertImageAtCursor: importExport.insertImageAtCursor,
    insertEmptyImageBlockAtCursor: importExport.insertEmptyImageBlockAtCursor,
    handleEditorDrop: importExport.handleEditorDrop,
    handleImport: importExport.handleImport,
    navigateToWiki: keyboard.navigateToWiki,
    canBackNote: keyboard.canBack,
    canForwardNote: keyboard.canForward,
    goBackNote: keyboard.goBack,
    goForwardNote: keyboard.goForward,
    handleToggleAreaNote: crud.handleToggleAreaNote,
    openCreatedNote: crud.openCreatedNote,
  };
}
