import { useMemo } from 'react';
import type {
  NoteViewSidebarLayout,
  NoteViewSidebarData,
  NoteViewSidebarHandlers,
  NoteViewSidebarProps,
} from './NoteViewSidebar';

export type UseNoteViewSidebarPropsInput = NoteViewSidebarLayout & NoteViewSidebarData & NoteViewSidebarHandlers;

export function useNoteViewSidebarProps(input: UseNoteViewSidebarPropsInput): NoteViewSidebarProps {
  const {
    hideLeftChrome,
    hideSecondaryChrome,
    hideNoteList,
    isMobile,
    isTablet,
    isCompactChrome,
    isWorkspacePanelMode,
    sidebarCollapsed,
    mobileSidebarOpen,
    accountId,
    c,
    dark,
    notes,
    folders,
    activeFolderId,
    activeTag,
    activeNoteCount,
    trashCount,
    starredCount,
    sidebarTodayCount,
    sidebarYesterdayCount,
    sidebarWeekCount,
    sidebarMonthCount,
    isTrash,
    noteListFilter,
    searchQuery,
    sidebarSearchQuery,
    knowledgeQueryInfo,
    workspaceActivation,
    isTraceLensMode,
    todayTraceKey,
    isTraceDayMode,
    traceDate,
    isTraceRangeMode,
    traceRange,
    currentTraceMonthKey,
    currentTraceQuarterKey,
    currentTraceYearKey,
    areaNotes,
    isTraceAreaMode,
    traceAreaId,
    isTraceDiscoveryMode,
    renamingFolderId,
    renameVal,
    showFolderForm,
    newFolderName,
    allTags,
    workspaceExpanded,
    isDashboardMode,
    smartCollectionCounts,
    pinnedWorkspaces,
    activeWorkspaceKind,
    activeWorkspaceId,
    recentWork,
    ruleCollections,
    ruleCollectionCounts,
    canCreateRuleCollection,
    databaseViews,
    databaseViewCounts,
    canCreateDatabaseView,
    databaseCreateSignal,
    savedViews,
    canSaveCurrentView,
    traceAreaProjection,
    traceAreaRange,
    activeDatabaseView,
    activeSmartCollection,
    activeRuleCollection,
    activeSavedView,
    folderLabel,
    traceLensMarkCount,
    isDatabaseViewMode,
    activeDatabaseViewNoteCount,
    recentNotes,
    visibleNotes,
    activeNotes,
    activeNoteId,
    safeNotesForDatabase,
    dashboard,
    sortOrder,
    sortDirection,
    starredFirst,
    listSectionPrefs,
    listDensity,
    showSortMenu,
    dragNoteId,
    editingLearningPathId,
    focusPresets,
    focusPresetTargets,
    focusSession,
    focusWorkspaceOptions,
    taskTemplates,
    journalTemplates,
    knowledgeMaintenance,
    unifiedWorkspaceDashboard,
    subjectWorkspaces,
    learningPathOverview,
    knowledgeTimeline,
    activitySummary,
    dashboardRecentActivity,
    dashboardLatestMilestone,
    evolutionInsights,
    searchInputRef,
    importInputRef,
    setSidebarCollapsed,
    setActiveFolderId,
    setActiveTag,
    setNoteListFilter,
    setSearchQuery,
    setSidebarSearchQuery,
    setShowShortcuts,
    openTraceDay,
    openTraceRange,
    openCreatedNote,
    openTraceArea,
    openTraceDiscovery,
    storeRenameFolder,
    setRenamingFolderId,
    setRenameVal,
    deleteFolder,
    setShowFolderForm,
    setNewFolderName,
    addFolder,
    setWorkspaceActivation,
    setTraceDate,
    setTraceRange,
    setTraceAreaId,
    setTraceAreaRange,
    setTraceDiscoveryMode,
    setWorkspaceExpanded,
    handleActivateDashboardWithTraceClear,
    handleActivateSmartCollection,
    handleClearSmartCollection,
    handleTogglePinWorkspace,
    isWorkspacePinned,
    handleActivateWorkspaceRef,
    handleUnpinWorkspace,
    handleMovePinnedWorkspace,
    handleClearRecentWork,
    handleActivateRuleCollection,
    handleClearRuleCollection,
    handleCreateRuleCollection,
    handleRenameRuleCollection,
    handleDeleteRuleCollection,
    handleActivateDatabaseView,
    handleClearDatabaseView,
    handleCreateDatabaseView,
    handleCreateDatabaseViewFromTemplate,
    handleRenameDatabaseView,
    handleDeleteDatabaseView,
    handleActivateSavedView,
    handleClearSavedView,
    handleCreateSavedView,
    handleRenameSavedView,
    handleDeleteSavedView,
    isWorkspaceKindActive,
    setMobileSidebarOpen,
    closeTraceLens,
    handleClearDashboard,
    setShowSortMenu,
    setSortOrder,
    setSortDirection,
    setStarredFirst,
    setListSectionPrefs,
    setListDensity,
    exportAllNotes,
    exportVaultBackup,
    openVaultRestore,
    openCreateEventDialog,
    createNote,
    setActiveNoteId,
    openNoteById,
    setMobileShowEditor,
    noteUpdate,
    setDragNoteId,
    duplicateNote,
    patchActiveDatabaseView,
    setDatabaseCreateSignal,
    setViewMode,
    handleLeaveDashboardForNote,
    handleResumeLastWorkspace,
    handleCreateFocusPreset,
    handleDeleteFocusPreset,
    handleActivateFocusPreset,
    handleExitFocusPreset,
    handleQuickCapture,
    handleCreateTask,
    handleCreateJournal,
    handleCreateReadingNote,
    handleCreateStudyNote,
    handleCreateTaskDatabase,
    handleCreateJournalDatabase,
    handleCreateProject,
    handleCreateProjectMilestone,
    handleOpenProjectNotes,
    handleEditProject,
    handleActivateSubjectWorkspace,
    handleOpenStudyCollection,
    handleOpenResearchCollection,
    handleOpenDiscover,
    handleOpenTimeline,
    handleOpenEvolution,
    handleNavigateToArea,
    handleCreateLearningPathStepNote,
    handleUpdateNoteProperties,
    handleNavigateToProjectEditor,
    setEditingLearningPathId,
    resumeWorkspace,
    handleEmptyTrash,
  } = input;

  return useMemo(() => ({
    layout: {
      hideLeftChrome,
      hideSecondaryChrome,
      hideNoteList,
      isMobile,
      isTablet,
      isCompactChrome,
      isWorkspacePanelMode,
      sidebarCollapsed,
      mobileSidebarOpen,
    },
    data: {
      accountId,
      c,
      dark,
      notes,
      folders,
      activeFolderId,
      activeTag,
      activeNoteCount,
      trashCount,
      starredCount,
      sidebarTodayCount,
      sidebarYesterdayCount,
      sidebarWeekCount,
      sidebarMonthCount,
      isTrash,
      noteListFilter,
      searchQuery,
      sidebarSearchQuery,
      knowledgeQueryInfo,
      workspaceActivation,
      isTraceLensMode,
      todayTraceKey,
      isTraceDayMode,
      traceDate,
      isTraceRangeMode,
      traceRange,
      currentTraceMonthKey,
      currentTraceQuarterKey,
      currentTraceYearKey,
      areaNotes,
      isTraceAreaMode,
      traceAreaId,
      isTraceDiscoveryMode,
      renamingFolderId,
      renameVal,
      showFolderForm,
      newFolderName,
      allTags,
      workspaceExpanded,
      isDashboardMode,
      smartCollectionCounts,
      pinnedWorkspaces,
      activeWorkspaceKind,
      activeWorkspaceId,
      recentWork,
      ruleCollections,
      ruleCollectionCounts,
      canCreateRuleCollection,
      databaseViews,
      databaseViewCounts,
      canCreateDatabaseView,
      databaseCreateSignal,
      savedViews,
      canSaveCurrentView,
      traceAreaProjection,
      traceAreaRange,
      activeDatabaseView,
      activeSmartCollection,
      activeRuleCollection,
      activeSavedView,
      folderLabel,
      traceLensMarkCount,
      isDatabaseViewMode,
      activeDatabaseViewNoteCount,
      recentNotes,
      visibleNotes,
      activeNotes,
      activeNoteId,
      safeNotesForDatabase,
      dashboard,
      sortOrder,
      sortDirection,
      starredFirst,
      listSectionPrefs,
      listDensity,
      showSortMenu,
      dragNoteId,
      editingLearningPathId,
      focusPresets,
      focusPresetTargets,
      focusSession,
      focusWorkspaceOptions,
      taskTemplates,
      journalTemplates,
      knowledgeMaintenance,
      unifiedWorkspaceDashboard,
      subjectWorkspaces,
      learningPathOverview,
      knowledgeTimeline,
      activitySummary,
      dashboardRecentActivity,
      dashboardLatestMilestone,
      evolutionInsights,
    },
    handlers: {
      searchInputRef,
      importInputRef,
      setSidebarCollapsed,
      setActiveFolderId,
      setActiveTag,
      setNoteListFilter,
      setSearchQuery,
      setSidebarSearchQuery,
      setShowShortcuts,
      openTraceDay,
      openTraceRange,
      openCreatedNote,
      openTraceArea,
      openTraceDiscovery,
      storeRenameFolder,
      setRenamingFolderId,
      setRenameVal,
      deleteFolder,
      setShowFolderForm,
      setNewFolderName,
      addFolder,
      setWorkspaceActivation,
      setTraceDate,
      setTraceRange,
      setTraceAreaId,
      setTraceAreaRange,
      setTraceDiscoveryMode,
      setWorkspaceExpanded,
      handleActivateDashboardWithTraceClear,
      handleActivateSmartCollection,
      handleClearSmartCollection,
      handleTogglePinWorkspace,
      isWorkspacePinned,
      handleActivateWorkspaceRef,
      handleUnpinWorkspace,
      handleMovePinnedWorkspace,
      handleClearRecentWork,
      handleActivateRuleCollection,
      handleClearRuleCollection,
      handleCreateRuleCollection,
      handleRenameRuleCollection,
      handleDeleteRuleCollection,
      handleActivateDatabaseView,
      handleClearDatabaseView,
      handleCreateDatabaseView,
      handleCreateDatabaseViewFromTemplate,
      handleRenameDatabaseView,
      handleDeleteDatabaseView,
      handleActivateSavedView,
      handleClearSavedView,
      handleCreateSavedView,
      handleRenameSavedView,
      handleDeleteSavedView,
      isWorkspaceKindActive,
      setMobileSidebarOpen,
      closeTraceLens,
      handleClearDashboard,
      setShowSortMenu,
      setSortOrder,
      setSortDirection,
      setStarredFirst,
      setListSectionPrefs,
      setListDensity,
      exportAllNotes,
      exportVaultBackup,
      openVaultRestore,
      openCreateEventDialog,
      createNote,
      setActiveNoteId,
      openNoteById,
      setMobileShowEditor,
      noteUpdate,
      setDragNoteId,
      duplicateNote,
      patchActiveDatabaseView,
      setDatabaseCreateSignal,
      setViewMode,
      handleLeaveDashboardForNote,
      handleResumeLastWorkspace,
      handleCreateFocusPreset,
      handleDeleteFocusPreset,
      handleActivateFocusPreset,
      handleExitFocusPreset,
      handleQuickCapture,
      handleCreateTask,
      handleCreateJournal,
      handleCreateReadingNote,
      handleCreateStudyNote,
      handleCreateTaskDatabase,
      handleCreateJournalDatabase,
      handleCreateProject,
      handleCreateProjectMilestone,
      handleOpenProjectNotes,
      handleEditProject,
      handleActivateSubjectWorkspace,
      handleOpenStudyCollection,
      handleOpenResearchCollection,
      handleOpenDiscover,
      handleOpenTimeline,
      handleOpenEvolution,
      handleNavigateToArea,
      handleCreateLearningPathStepNote,
      handleUpdateNoteProperties,
      handleNavigateToProjectEditor,
      setEditingLearningPathId,
      resumeWorkspace,
      handleEmptyTrash,
    },
  }), [
    hideLeftChrome, hideSecondaryChrome, hideNoteList, isMobile, isTablet, isCompactChrome,
    isWorkspacePanelMode, sidebarCollapsed, mobileSidebarOpen, accountId, c, dark, notes, folders,
    activeFolderId, activeTag, activeNoteCount, trashCount, starredCount,
    sidebarTodayCount, sidebarYesterdayCount, sidebarWeekCount, sidebarMonthCount, isTrash, noteListFilter, searchQuery, sidebarSearchQuery,
    knowledgeQueryInfo, workspaceActivation, isTraceLensMode, todayTraceKey, isTraceDayMode,
    traceDate, isTraceRangeMode, traceRange, currentTraceMonthKey, currentTraceQuarterKey,
    currentTraceYearKey, areaNotes, isTraceAreaMode, traceAreaId, isTraceDiscoveryMode,
    renamingFolderId, renameVal, showFolderForm, newFolderName, allTags, workspaceExpanded,
    isDashboardMode, smartCollectionCounts, pinnedWorkspaces, activeWorkspaceKind,
    activeWorkspaceId, recentWork, ruleCollections, ruleCollectionCounts, canCreateRuleCollection,
    databaseViews, databaseViewCounts, canCreateDatabaseView, databaseCreateSignal, savedViews,
    canSaveCurrentView, traceAreaProjection, traceAreaRange, activeDatabaseView,
    activeSmartCollection, activeRuleCollection, activeSavedView, folderLabel, traceLensMarkCount,
    isDatabaseViewMode, activeDatabaseViewNoteCount, recentNotes, visibleNotes, activeNotes,
    activeNoteId, safeNotesForDatabase, dashboard, sortOrder, sortDirection, listDensity, showSortMenu, dragNoteId,
    editingLearningPathId, focusPresets, focusPresetTargets, focusSession, focusWorkspaceOptions,
    taskTemplates, journalTemplates, knowledgeMaintenance, unifiedWorkspaceDashboard,
    subjectWorkspaces, learningPathOverview, knowledgeTimeline, activitySummary,
    dashboardRecentActivity, dashboardLatestMilestone, evolutionInsights, searchInputRef,
    importInputRef, setSidebarCollapsed, setActiveFolderId, setActiveTag, setSearchQuery, setSidebarSearchQuery,
    setShowShortcuts, openTraceDay, openTraceRange, openCreatedNote,
    openTraceArea, openTraceDiscovery, storeRenameFolder, setRenamingFolderId, setRenameVal,
    deleteFolder, setShowFolderForm, setNewFolderName, addFolder, setWorkspaceActivation,
    setTraceDate, setTraceRange, setTraceAreaId, setTraceAreaRange, setTraceDiscoveryMode,
    setWorkspaceExpanded, handleActivateDashboardWithTraceClear, handleActivateSmartCollection,
    handleClearSmartCollection, handleTogglePinWorkspace, isWorkspacePinned,
    handleActivateWorkspaceRef, handleUnpinWorkspace, handleMovePinnedWorkspace,
    handleClearRecentWork, handleActivateRuleCollection, handleClearRuleCollection,
    handleCreateRuleCollection, handleRenameRuleCollection, handleDeleteRuleCollection,
    handleActivateDatabaseView, handleClearDatabaseView, handleCreateDatabaseView,
    handleCreateDatabaseViewFromTemplate, handleRenameDatabaseView, handleDeleteDatabaseView,
    handleActivateSavedView, handleClearSavedView, handleCreateSavedView, handleRenameSavedView,
    handleDeleteSavedView, isWorkspaceKindActive, setMobileSidebarOpen, closeTraceLens,
    handleClearDashboard, setShowSortMenu, setSortOrder, setSortDirection, setListDensity, exportAllNotes, exportVaultBackup, openVaultRestore, openCreateEventDialog,
    createNote, setActiveNoteId, openNoteById, setMobileShowEditor, noteUpdate, setDragNoteId, duplicateNote,
    patchActiveDatabaseView, setDatabaseCreateSignal, setViewMode, handleLeaveDashboardForNote,
    handleResumeLastWorkspace, handleCreateFocusPreset, handleDeleteFocusPreset,
    handleActivateFocusPreset, handleExitFocusPreset, handleQuickCapture, handleCreateTask,
    handleCreateJournal, handleCreateReadingNote, handleCreateStudyNote, handleCreateTaskDatabase,
    handleCreateJournalDatabase, handleCreateProject, handleCreateProjectMilestone,
    handleOpenProjectNotes, handleEditProject, handleActivateSubjectWorkspace,
    handleOpenStudyCollection, handleOpenResearchCollection, handleOpenDiscover, handleOpenTimeline,
    handleOpenEvolution, handleNavigateToArea, handleCreateLearningPathStepNote,
    handleUpdateNoteProperties, handleNavigateToProjectEditor, setEditingLearningPathId,
    resumeWorkspace, handleEmptyTrash,
  ]);
}
