import type { Dispatch, MutableRefObject, RefObject, SetStateAction } from 'react';
import type { BlockEditorHandle } from '../../BlockEditor';
import type { EditorMode } from '../../editorMode';
import type { EditorSearchScope } from '../../editorSearch';
import type { KnowledgeContextTab } from '../../features/knowledge/components/KnowledgeContextPanel';
import type { EventFormValues, TraceRangeLens } from '../../features/knowledge';
import type { NoteBase as Note } from '../../noteUtils';
import type { EventDialogState, MilestoneDialogState } from '../useNoteViewState';

export interface UseNoteViewActionsParams {
  notes: Note[];
  activeNote: Note | null;
  activeNoteId: string | null;
  activeFolderId: string | null | 'trash' | 'starred';
  isTrash: boolean;
  traceAreaId: string | null;
  viewMode: EditorMode;
  showSortMenu: boolean;
  newFolderName: string;
  eventDialog: EventDialogState | null;
  milestoneDialog: MilestoneDialogState | null;
  titleInputRef: RefObject<HTMLInputElement | null>;
  titleComposingRef: MutableRefObject<boolean>;
  docCopyTimerRef: MutableRefObject<ReturnType<typeof setTimeout> | null>;
  blockEditorRef: RefObject<BlockEditorHandle | null>;
  searchInputRef: RefObject<HTMLInputElement | null>;
  openCreateEventDialogRef: MutableRefObject<(defaults?: Partial<EventFormValues>) => void>;
  setViewMode: Dispatch<SetStateAction<EditorMode>>;
  setActiveFolderId: Dispatch<SetStateAction<string | null | 'trash' | 'starred'>>;
  setSearchQuery: Dispatch<SetStateAction<string>>;
  setShowFolderForm: Dispatch<SetStateAction<boolean>>;
  setNewFolderName: Dispatch<SetStateAction<string>>;
  setEventDialog: Dispatch<SetStateAction<EventDialogState | null>>;
  setMilestoneDialog: Dispatch<SetStateAction<MilestoneDialogState | null>>;
  setCreateProjectDialogOpen: Dispatch<SetStateAction<boolean>>;
  setCreateMilestoneDialogOpen: Dispatch<SetStateAction<boolean>>;
  setTraceDate: Dispatch<SetStateAction<string | null>>;
  setTraceRange: Dispatch<SetStateAction<TraceRangeLens | null>>;
  setTraceAreaId: Dispatch<SetStateAction<string | null>>;
  setTraceAreaRange: Dispatch<SetStateAction<TraceRangeLens | null>>;
  setTraceDiscoveryMode: Dispatch<SetStateAction<boolean>>;
  setWorkspaceActivation: (activation: import('../../features/knowledge').WorkspaceActivation) => void;
  setShowShortcuts: Dispatch<SetStateAction<boolean>>;
  setShowSortMenu: Dispatch<SetStateAction<boolean>>;
  setFocusMode: Dispatch<SetStateAction<boolean>>;
  setDocCopied: Dispatch<SetStateAction<boolean>>;
  setSearchScope: Dispatch<SetStateAction<EditorSearchScope>>;
  setDocumentSearchOpen: Dispatch<SetStateAction<boolean>>;
  setActiveTag: Dispatch<SetStateAction<string | null>>;
  setMobileSidebarOpen: Dispatch<SetStateAction<boolean>>;
  setExpandedGraphNodes: Dispatch<SetStateAction<string[]>>;
  setIsDragOver: Dispatch<SetStateAction<boolean>>;
  setTitleDraft: Dispatch<SetStateAction<string>>;
  setActiveNoteId: (id: string) => void;
  setShowRightPanel: Dispatch<SetStateAction<boolean>>;
  setRightPanel: Dispatch<SetStateAction<KnowledgeContextTab>>;
  setEditingLearningPathId: Dispatch<SetStateAction<string | null | undefined>>;
  updateNote: (id: string, patch: Partial<Pick<Note, 'title' | 'body' | 'folderId' | 'starred' | 'properties' | 'relations'>>) => void;
  storeCreateNote: (initial?: Partial<Pick<Note, 'title' | 'body' | 'folderId'>> & { folderContext?: string | null }) => string;
  storeCreateFolder: (name: string) => string;
  storeDuplicateNote: (note: Note) => void;
  storeDeleteFolder: (id: string) => void;
  importNote: (note: Note) => void;
  flushPendingSync: () => void;
  syncNoteToDB: (note: Note) => Promise<boolean | void>;
  handleLeaveDashboardForNote: (id: string) => void;
  handleActivateSmartCollection: (collection: import('../../features/knowledge').SmartCollection) => void;
  handleActivateDashboard: () => void;
  resetBrowseScope: () => void;
  isMobile: boolean;
}

export type OpenCreatedNote = (id: string) => string;
export type CreateNoteFn = (initial?: Partial<Pick<Note, 'title' | 'body' | 'folderId'>>) => string;
export type NoteUpdateFn = (id: string, patch: Partial<Pick<Note, 'title' | 'body' | 'folderId' | 'starred' | 'properties' | 'relations'>>) => void;
