export type LocalDatabaseErrorCode =
  | 'CAPABILITY_REQUIRED' | 'INVALID_NAMESPACE' | 'UNSAFE_NAMESPACE'
  | 'OPEN_FAILED' | 'OPEN_BLOCKED' | 'UNSUPPORTED_SCHEMA_VERSION'
  | 'DATABASE_CLOSED' | 'STALE_CONNECTION' | 'MALFORMED_METADATA'
  | 'NAMESPACE_MISMATCH' | 'GENERATION_NOT_FOUND' | 'GENERATION_NOT_ACTIVE'
  | 'STALE_GENERATION' | 'INVALID_GENERATION_TRANSITION'
  | 'ENTITY_NOT_FOUND' | 'ENTITY_ALREADY_EXISTS' | 'EXPECTED_REVISION_REQUIRED'
  | 'STALE_REVISION' | 'TOMBSTONE_REACTIVATION_BLOCKED' | 'CORRUPT_PERSISTED_RECORD'
  | 'INVALID_ENTITY' | 'INVALID_OUTBOX' | 'INVALID_RESERVED_RECORD'
  | 'OUTBOX_NOT_FOUND' | 'INVALID_OUTBOX_TRANSITION' | 'LEASE_OWNER_MISMATCH'
  | 'INVALID_OUTBOX_QUERY' | 'OUTBOX_SEQUENCE_GAP' | 'OUTBOX_IDEMPOTENCY_MISMATCH'
  | 'TRANSACTION_ABORTED' | 'TRANSACTION_FAILED'
  | 'INVALID_RESTORE_PROTOCOL' | 'INVALID_RESTORE_PACKAGE' | 'PACKAGE_DIGEST_MISMATCH'
  | 'PACKAGE_ENTITY_COUNT_MISMATCH' | 'DUPLICATE_RESTORE_ENTITY' | 'UNSUPPORTED_RESTORE_DOMAIN'
  | 'RESTORE_PAYLOAD_TOO_LARGE' | 'RESTORE_NAMESPACE_MISMATCH' | 'RESTORE_PROJECT_MISMATCH'
  | 'RESTORE_SESSION_CONFLICT' | 'RESTORE_ALREADY_COMMITTED' | 'RESTORE_CANCELLED'
  | 'RESTORE_ACTIVE_GENERATION_CHANGED' | 'RESTORE_ENTITY_REVISION_CONFLICT'
  | 'RESTORE_TOMBSTONE_CONFLICT' | 'REMOTE_RESURRECTION_UNSUPPORTED'
  | 'RESTORE_UNSETTLED_OUTBOX_CONFLICT'
  | 'RESTORE_TRANSACTION_FAILED'
  | 'INVALID_LEGACY_MIGRATION' | 'LEGACY_SOURCE_UNAVAILABLE'
  | 'LEGACY_SOURCE_AUTHORITY_REQUIRED' | 'LEGACY_SOURCE_AUTHORITY_CONFLICT'
  | 'LEGACY_SOURCE_AUTHORITY_REVOKED' | 'LEGACY_SOURCE_IDENTITY_MISMATCH'
  | 'MIGRATION_SOURCE_CHANGED' | 'MIGRATION_SESSION_CONFLICT' | 'MIGRATION_CANCELLED'
  | 'CUTOVER_SESSION_CONFLICT' | 'CUTOVER_PRECONDITION_FAILED'
  | 'CUTOVER_ALREADY_ACTIVATED' | 'CUTOVER_CANCELLED'
  | 'CUTOVER_RECOVERY_AUTHORIZATION_REQUIRED' | 'CUTOVER_CONFIRMATION_FAILED'
  | 'ACTIVE_GENERATION_TRANSITION_REQUIRES_PROTOCOL'
  | 'CUTOVER_FENCE_RECOVERY_REQUIRED' | 'CUTOVER_FENCE_CLEANUP_FAILED'
  | 'CUTOVER_FENCE_IDENTITY_MISMATCH' | 'CUTOVER_FENCE_REAPPEARED'
  | 'CUTOVER_FENCE_INSTANCE_MISMATCH' | 'CUTOVER_FENCE_OWNERSHIP_CONFLICT'
  | 'CUTOVER_FENCE_RECOVERY_INCOMPLETE' | 'CUTOVER_FENCE_SET_CHANGED'
  | 'CUTOVER_MULTIPLE_FENCES_PRESENT' | 'CUTOVER_FOREIGN_FENCE_PRESENT'
  | 'CUTOVER_FENCE_ARTIFACT_MALFORMED' | 'CUTOVER_FENCE_VAULT_NOT_CLEAR'
  | 'CUTOVER_FENCE_NOT_SETTLED' | 'CUTOVER_FENCE_SETTLEMENT_CONFLICT'
  | 'CUTOVER_FENCE_SETTLEMENT_ORPHANED' | 'CUTOVER_FENCE_SETTLEMENT_MALFORMED'
  | 'CUTOVER_FENCE_OPERATIONALLY_BLOCKED' | 'CUTOVER_UNSUPPORTED_SHARED_FENCE';

export class LocalDatabaseError extends Error {
  readonly code: LocalDatabaseErrorCode;
  readonly operation: string;

  constructor(code: LocalDatabaseErrorCode, operation: string) {
    super(`${code}:${operation}`);
    this.name = 'LocalDatabaseError';
    this.code = code;
    this.operation = operation;
  }
}

export function localDatabaseError(error: unknown, operation: string): LocalDatabaseError {
  if (error instanceof LocalDatabaseError) return error;
  if (error instanceof DOMException && error.name === 'VersionError') {
    return new LocalDatabaseError('UNSUPPORTED_SCHEMA_VERSION', operation);
  }
  return new LocalDatabaseError('TRANSACTION_FAILED', operation);
}
